"""Reference qpos and reset-pose constants for the 2F-85 (Robotiq) gripper,
the 22-DOF Sharpa hand, and the Franka FR3 arm.

The reset poses at the bottom are the agreed handshake between server and
client — must stay in sync with the client-side constants in ``hand_droid``.

Also the single source of truth for MuJoCo scene XML paths (bottom of file):
use the robot XMLs (``*_FR3_XML``) for FK/IK and rendering; the scene XMLs
(``*_SCENE_XML``) add a colliding floor.
"""

from pathlib import Path

import numpy as np

# Settled qpos for the 8 2F-85 gripper joints (qpos[7:] in fr3_robotiq.xml),
# captured by mj_step convergence at ctrl=0 (open) and ctrl=0.8 (closed).
# fmt: off
GRIPPER_QPOS_OPEN = np.array([
    0.05685287, 0.0001478, 0.05684168, -0.05472553,
    0.05685287, 0.0001478, 0.05684095, -0.0547242,
])
GRIPPER_QPOS_CLOSED = np.array([
    0.77526133, 0.00017553, 0.77537824, -0.74554769,
    0.77526154, 0.00017356, 0.77538077, -0.74552788,
])
# fmt: on


def lerp_gripper_qpos(gripper_position: float) -> np.ndarray:
    """Linear interpolation of the 8 2F-85 gripper joints for
    `gripper_position` in [0, 1] (0 = open, 1 = closed)."""
    g = float(gripper_position)
    return (1.0 - g) * GRIPPER_QPOS_OPEN + g * GRIPPER_QPOS_CLOSED


# RLDS wrist-stream size and key.
RLDS_H, RLDS_W = 180, 320
WRIST_CAM_KEY = "wrist_image_left"

# Mean wrist-camera parameters across DROID (fallback + per-episode optimization
# seed): cam_to_gripper [tx,ty,tz,rx,ry,rz] (m + XYZ euler rad) in the EE frame,
# and [fx,fy,cx,cy] intrinsics at RLDS 320x180.
# fmt: off
DEFAULT_CAM_TO_GRIPPER = np.array([
    -0.07603768464487827, 0.030755540645682176, -0.005156207813252746,
    -0.33089674351839693, 0.0052405001986228815, -1.5305427085990393,
])
DEFAULT_WRIST_INTRINSICS = np.array([
    182.7151540905966, 182.7151540905966, 160.14853881286072, 89.9061105794428,
])
# fmt: on


# 22-D Sharpa hand qpos (qpos[7:7+22] in fr3_sharpa_roll45.xml). Joint order:
#   thumb (CMC_FE, CMC_AA, MCP_FE, MCP_AA, IP),
#   index/middle/ring (MCP_FE, MCP_AA, PIP, DIP),
#   pinky (CMC, MCP_FE, MCP_AA, PIP, DIP).
# fmt: off
SHARPA_HAND_QPOS_CLOSED = np.array(
    [
        1.73, 0.026, -0.005, -0.1, 0.3,  # Thumb
        1.348, 0.03, 0.1, 0.101,           # Index
        1.381, 0.027, 0.1, 0.101,          # Middle
        1.34, 0.025, 0.1, 0.101,           # Ring
        # 0.162, 1.292, 0.167, 0.101, 0.102, # Pinky
        0.25, 1.5, 0.1, 0.101, 0.102, # Pinky
    ]
)
SHARPA_HAND_QPOS_OPEN = np.array(
    [
        1.661, -0.249, -0.423, 0.06982, 0.40135, # Thumb
        0.7, 0.073, 0.101, 0.239,                # Index
        0.7, 0.07, 0.101, 0.195,                 # Middle
        0.7, 0.068, 0.101, 0.252,                # Ring
        0.106, 0.7, 0.152, 0.101, 0.309,         # Pinky
    ]
)
# fmt: on


# Joint count per finger, in SHARPA_HAND_QPOS_OPEN/CLOSED order (sum = 22).
SHARPA_FINGER_JOINT_COUNTS = (5, 4, 4, 4, 5)
SHARPA_FINGER_NAMES = ("thumb", "index", "middle", "ring", "pinky")


def lerp_sharpa_hand_qpos(
    gripper_position: float, finger_weights: np.ndarray | None = None
) -> np.ndarray:
    """Sharpa-hand counterpart of `lerp_gripper_qpos`. `gripper_position` is
    clipped to [0, 1]. Optional length-5 `finger_weights` (in
    SHARPA_FINGER_NAMES order) scale each finger's closing fraction
    independently — e.g. weight 0.5 means that finger reaches 50% closed at
    `gripper_position=1`. `None` (default) closes every finger fully.
    """
    g = float(np.clip(gripper_position, 0.0, 1.0))
    if finger_weights is None:
        return (1.0 - g) * SHARPA_HAND_QPOS_OPEN + g * SHARPA_HAND_QPOS_CLOSED
    fw = np.asarray(finger_weights, dtype=np.float64)
    if fw.shape != (5,):
        raise ValueError(
            f"finger_weights must be length 5 in {SHARPA_FINGER_NAMES} order; got shape {fw.shape}"
        )
    g_eff = g * np.repeat(fw, SHARPA_FINGER_JOINT_COUNTS)
    return (1.0 - g_eff) * SHARPA_HAND_QPOS_OPEN + g_eff * SHARPA_HAND_QPOS_CLOSED


# --- Agreed-upon client/server reset poses ---

# Sharpa client arm reset; mirrors hand_droid/droid/franka_sharpa_env.py
# (RESET_ARM_QPOS). Generated by
# scripts/tuning/find_sharpa_agreed_pose_fixedpoint.py.
SHARPA_ARM_QPOS = np.array(
    [-0.134, -0.516, 0.002, -2.335, -0.439, 1.904, -0.230], dtype=np.float32
)

# DROID reset arm pose; mirrors hand_droid/droid/robot_env.py. Used by the
# plain Robotiq client and as the fingertip-target arm pose when fitting
# SHARPA_ARM_QPOS / UMI_ARM_QPOS.
DROID_ARM_QPOS = np.array(
    [0.0, -np.pi / 5, 0.0, -4 * np.pi / 5, 0.0, 3 * np.pi / 5, 0.0], dtype=np.float32
)

# UMI client arm reset; generated by scripts/compute_franka_umi_reset_pose.py
# to land UMI fingertips at the Robotiq fingertip positions at DROID_ARM_QPOS.
UMI_ARM_QPOS = np.array(
    [0.003, -0.721, 0.004, -2.468, 0.003, 1.833, 0.790], dtype=np.float32
)

# UMI tendon-coupled fingers at reset (fully open). Equivalent to
# `umi_finger_qpos_from_gripper(GRIPPER_OPEN_SCALAR)`.
UMI_HAND_QPOS_OPEN = np.array([0.04, 0.04], dtype=np.float32)

# I2RT YAM 6-DOF arm reset; generated by scratch/solve_yam_default_pose.py to
# land the YAM left/right gripper tips at the Robotiq tips at DROID_ARM_QPOS
# (mink IK, position weight 1.0 / orientation 0.05). With the YAM base shifted
# +0.15m z (see yam_linear.xml), position matches to ~0.6 mm and orientation to
# ~0.065 rad (joint4 sits at its -pi/2 limit but the residual is negligible).
YAM_ARM_QPOS = np.array(
    [-0.0098, 1.8892, 1.9543, -1.5708, -0.0004, -0.0093], dtype=np.float32
)

# YAM linear gripper slide joints (joint7/joint8); larger = fingers further
# apart. Slide range is [0, 0.0475].
YAM_GRIPPER_QPOS_OPEN = np.array([0.0475, 0.0475], dtype=np.float32)
YAM_GRIPPER_QPOS_CLOSED = np.array([0.0, 0.0], dtype=np.float32)

# Robotiq/UMI wire convention for the gripper scalar: 0 = open, 1 = closed.
GRIPPER_OPEN_SCALAR = 0.0

# YAM deployment camera defaults. Unlike the Franka clients, the YAM client sends
# no camera params, so the server renders the wrist mask from these:
# YAM_CAM_TO_GRIPPER is the wrist cam-to-gripper 6-vec [xyz (m), euler-xyz (rad)]
# for the real YAM rig, and YAM_WRIST_INTRINSIC_FY is the wrist focal length fy
# (px) at RLDS 320x180. YAM's per-robot cam offset relative to the DROID rig is
# identity, so the mount is folded entirely into this extrinsic.
YAM_CAM_TO_GRIPPER = np.array(
    [-0.09105, 0.03311, 0.02103, *np.deg2rad([-28.50, -0.19, -90.36])]
)
YAM_WRIST_INTRINSIC_FY = float(DEFAULT_WRIST_INTRINSICS[1])


# ===========================================================================
# MuJoCo scene XML paths (single source of truth)
# ===========================================================================
# Importers should reference these constants instead of hand-rolling paths so
# that asset relocations only need to be made in one place.

_REPO_ROOT = Path(__file__).resolve().parents[2]
_ASSETS = _REPO_ROOT / "assets"

# Franka FR3 + Robotiq 2F-85.
ROBOTIQ_FR3_XML = _ASSETS / "franka_fr3_robotiq" / "fr3_robotiq.xml"
ROBOTIQ_SCENE_XML = _ASSETS / "franka_fr3_robotiq" / "scene.xml"

# Franka FR3 + Sharpa hand (angled mount: hand rotated 180 deg about the wrist
# approach axis; the IK defaults in ``sharpa_ik_transform.py`` are tuned for
# this geometry).
SHARPA_FR3_XML = _ASSETS / "franka_fr3_sharpa_angled" / "fr3_sharpa_angled.xml"
SHARPA_SCENE_XML = _ASSETS / "franka_fr3_sharpa_angled" / "scene.xml"

# Franka FR3 + UMI parallel-jaw gripper (Panda hand body wearing UMI tri-finger
# pads; mounted at -45 deg roll so its jaws co-locate with the Robotiq jaws).
UMI_FR3_XML = _ASSETS / "franka_fr3_umi" / "fr3_umi.xml"
UMI_SCENE_XML = _ASSETS / "franka_fr3_umi" / "scene.xml"

# I2RT YAM 6-DOF arm + linear (parallel-slide) gripper. Base shifted +0.15m z so
# the YAM tips land on the Robotiq tips at DROID_ARM_QPOS (see YAM_ARM_QPOS).
YAM_LINEAR_XML = _ASSETS / "yam_linear" / "yam_linear.xml"
YAM_LINEAR_SCENE_XML = _ASSETS / "yam_linear" / "scene.xml"
